stages:
  - test
  - publish

services:
  - docker:dind

lint:
  image: simonlorenz/docker-with-compose
  stage: test
  script:
    - docker-compose -f docker-compose.ci.yml run server-test npm run lint

test:
  image: simonlorenz/docker-with-compose
  stage: test
  script:
    - docker-compose -f docker-compose.ci.yml run server-test npm run test

production:
  image: docker:latest
  stage: publish
  script:
    - >
      docker build
      -t simonlorenz/mampfalot:latest
      -t simonlorenz/mampfalot:$CI_COMMIT_TAG
      -f ./server/Dockerfile.prod
      ./server

    - >
      docker build
      -t simonlorenz/mampfalot-client:latest
      -t simonlorenz/mampfalot-client:$CI_COMMIT_TAG
      -f ./client/Dockerfile.prod
      ./client

    - docker login -u simonlorenz -p $DOCKER_ACCESS_TOKEN

    - docker push simonlorenz/mampfalot:latest
    - docker push simonlorenz/mampfalot:$CI_COMMIT_TAG
    - docker push simonlorenz/mampfalot-client:latest
    - docker push simonlorenz/mampfalot-client:$CI_COMMIT_TAG
  rules:
    - if: '$CI_COMMIT_TAG != null'

dev:
  image: docker:latest
  stage: publish
  script:
    - docker build -t simonlorenz/mampfalot:dev -f ./server/Dockerfile.prod ./server
    - docker build -t simonlorenz/mampfalot-client:dev -f ./client/Dockerfile.dev ./client

    - docker login -u simonlorenz -p $DOCKER_ACCESS_TOKEN

    - docker push simonlorenz/mampfalot:dev
    - docker push simonlorenz/mampfalot-client:dev
  rules:
    - if: '$CI_COMMIT_REF_NAME == "dev"'
