version: '3.6'

services:
  server:
    build: .
    container_name: mampfalot
    command: npm run start:dev
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    networks:
      - app
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=info
      - DATABASE_URL=postgres://postgres:root@postgres:5432/mampfalot
      - SECRET_KEY=123456

  postgres:
    image: postgres:11
    container_name: mampfalot-postgres
    environment:
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_DB=mampfalot"
      - "PGDATA=/var/lib/postgresql/data"
    networks:
      - app
      - pgadmin
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: mampfalot-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
       - ./.docker/pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - pgadmin

networks:
  pgadmin:
    driver: bridge
  app:
    driver: bridge

volumes:
  postgres:
