FROM node:16.5.0-alpine

WORKDIR /server

COPY package*.json ./

RUN npm ci --production && npm cache clean --force

COPY ./src ./src
COPY app.js ./
COPY LICENSE ./

EXPOSE 5000

CMD ["node", "app.js"]
